webtalk_init -webtalk_dir /home/jal/dhu_gse_workspace_06_02_bitrev8/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jun 2 16:49:58 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210904876_1777501295_210584454_104" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "i1htk59u834mc14oua12cpmd5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS release 6.6 (Final)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1433267903000" -context "sdk\\\\hardware/1433267903000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1433267903000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1433267903000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1433267903000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1433267903000"
webtalk_add_data -client sdk -key Device -value "7z045" -context "sdk\\\\hardware/1433267903000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1433267903000"
webtalk_transmit -clientid 2835012110 -regid "210904876_1777501295_210584454_104" -xml /home/jal/dhu_gse_workspace_06_02_bitrev8/webtalk/usage_statistics_ext_sdk.xml -html /home/jal/dhu_gse_workspace_06_02_bitrev8/webtalk/usage_statistics_ext_sdk.html -wdm /home/jal/dhu_gse_workspace_06_02_bitrev8/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
